require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RunnerStatusCodesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # RunnerStatusCode. As you add validations to RunnerStatusCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RunnerStatusCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all runner_status_codes as @runner_status_codes" do
      runner_status_code = RunnerStatusCode.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:runner_status_codes)).to eq([runner_status_code])
    end
  end

  describe "GET show" do
    it "assigns the requested runner_status_code as @runner_status_code" do
      runner_status_code = RunnerStatusCode.create! valid_attributes
      get :show, {:id => runner_status_code.to_param}, valid_session
      expect(assigns(:runner_status_code)).to eq(runner_status_code)
    end
  end

  describe "GET new" do
    it "assigns a new runner_status_code as @runner_status_code" do
      get :new, {}, valid_session
      expect(assigns(:runner_status_code)).to be_a_new(RunnerStatusCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested runner_status_code as @runner_status_code" do
      runner_status_code = RunnerStatusCode.create! valid_attributes
      get :edit, {:id => runner_status_code.to_param}, valid_session
      expect(assigns(:runner_status_code)).to eq(runner_status_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RunnerStatusCode" do
        expect {
          post :create, {:runner_status_code => valid_attributes}, valid_session
        }.to change(RunnerStatusCode, :count).by(1)
      end

      it "assigns a newly created runner_status_code as @runner_status_code" do
        post :create, {:runner_status_code => valid_attributes}, valid_session
        expect(assigns(:runner_status_code)).to be_a(RunnerStatusCode)
        expect(assigns(:runner_status_code)).to be_persisted
      end

      it "redirects to the created runner_status_code" do
        post :create, {:runner_status_code => valid_attributes}, valid_session
        expect(response).to redirect_to(RunnerStatusCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved runner_status_code as @runner_status_code" do
        post :create, {:runner_status_code => invalid_attributes}, valid_session
        expect(assigns(:runner_status_code)).to be_a_new(RunnerStatusCode)
      end

      it "re-renders the 'new' template" do
        post :create, {:runner_status_code => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested runner_status_code" do
        runner_status_code = RunnerStatusCode.create! valid_attributes
        put :update, {:id => runner_status_code.to_param, :runner_status_code => new_attributes}, valid_session
        runner_status_code.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested runner_status_code as @runner_status_code" do
        runner_status_code = RunnerStatusCode.create! valid_attributes
        put :update, {:id => runner_status_code.to_param, :runner_status_code => valid_attributes}, valid_session
        expect(assigns(:runner_status_code)).to eq(runner_status_code)
      end

      it "redirects to the runner_status_code" do
        runner_status_code = RunnerStatusCode.create! valid_attributes
        put :update, {:id => runner_status_code.to_param, :runner_status_code => valid_attributes}, valid_session
        expect(response).to redirect_to(runner_status_code)
      end
    end

    describe "with invalid params" do
      it "assigns the runner_status_code as @runner_status_code" do
        runner_status_code = RunnerStatusCode.create! valid_attributes
        put :update, {:id => runner_status_code.to_param, :runner_status_code => invalid_attributes}, valid_session
        expect(assigns(:runner_status_code)).to eq(runner_status_code)
      end

      it "re-renders the 'edit' template" do
        runner_status_code = RunnerStatusCode.create! valid_attributes
        put :update, {:id => runner_status_code.to_param, :runner_status_code => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested runner_status_code" do
      runner_status_code = RunnerStatusCode.create! valid_attributes
      expect {
        delete :destroy, {:id => runner_status_code.to_param}, valid_session
      }.to change(RunnerStatusCode, :count).by(-1)
    end

    it "redirects to the runner_status_codes list" do
      runner_status_code = RunnerStatusCode.create! valid_attributes
      delete :destroy, {:id => runner_status_code.to_param}, valid_session
      expect(response).to redirect_to(runner_status_codes_url)
    end
  end

end
